/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.awt.event.*;
import java.awt.*;
import javax.swing.*;

/**
 *
 * @author Usuario
 */
public class Marco extends javax.swing.JFrame {

    private JButton[][] botones;

    /**
     * Creates new form Marco
     */
    public Marco() {
        initComponents();

        panelJuego.setLayout(new GridLayout(13, 13));
        botones = new JButton[14][14];

//        for (int i = 1; i < 14; i++) {
//            JButton jButton = new JButton();
//            jButton.addActionListener(new ListenerBoton(0, i));
//            jButton.setPreferredSize(new Dimension(50, 50));
//            panelJuego.add(jButton);
//            botones[0][i] = jButton;
//            botones[0][i].setText(String.valueOf(i));
//        }
        for (int i = 0; i < 13; i++) {
            for (int j = 0; j < 13; j++) {
                JButton jButton = new JButton();
                jButton.addActionListener(new ListenerBoton(i, j));
                jButton.setPreferredSize(new Dimension(50, 50));
                jButton.setFont(new Font("Arial", Font.PLAIN, 10));
                panelJuego.add(jButton);
                botones[i][j] = jButton;
                ImageIcon img = new ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\Arcoiris\\imagenes\\negraQ.png");
                Image imag = img.getImage();
                Image newimg = imag.getScaledInstance(30, 30,  java.awt.Image.SCALE_SMOOTH);
                img = new ImageIcon(newimg);
//                botones[i][j].setIcon(img);
//                botones[i][j].setText(String.valueOf(i) + "," + String.valueOf(j));
            }
        }
//        botones[6][6].setBackground(Color.RED);

        for (int i = 0; i < 13; i++) {
            for (int j = 0; j < 13; j++) {
                if (Prueba.medirDistanciaMarco(i, j, 1)) {
                    botones[i][j].setBackground(Color.RED);
                } else if (Prueba.medirDistanciaMarco(i, j, 2)) {
                    botones[i][j].setBackground(Color.ORANGE);
                } else if (Prueba.medirDistanciaMarco(i, j, 3)) {
                    botones[i][j].setBackground(Color.YELLOW);
                } else if (Prueba.medirDistanciaMarco(i, j, 4)) {
                    botones[i][j].setBackground(Color.GREEN);
                } else if (Prueba.medirDistanciaMarco(i, j, 5)) {
                    botones[i][j].setBackground(Color.CYAN);
                } else if (Prueba.medirDistanciaMarco(i, j, 6)) {
                    botones[i][j].setBackground(Color.BLUE);
                } else {
                    botones[i][j].setBackground(Color.WHITE);
                }
            }
        }
//        for (int i = 1; i < 1; i++) {
//            for (int j = 0; j < 1; j++) {
//                JButton jButton = new JButton();
//                panelJuego.add(jButton);
//                botones[i][j] = jButton;
//            }
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelJuego = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelJuegoLayout = new javax.swing.GroupLayout(panelJuego);
        panelJuego.setLayout(panelJuegoLayout);
        panelJuegoLayout.setHorizontalGroup(
            panelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );
        panelJuegoLayout.setVerticalGroup(
            panelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(panelJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(panelJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Marco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Marco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Marco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Marco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Marco().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelJuego;
    // End of variables declaration//GEN-END:variables

    private class ListenerBoton implements ActionListener {

        private int x;
        private int y;

        public ListenerBoton(int i, int j) {
// en el constructor se almacena la fila y columna que se presionó
            x = i;
            y = j;
        }

        public void actionPerformed(ActionEvent e) {
// cuando se presiona un botón, se ejecutará este método
            clickBoton(x, y);
        }
    }

    private void clickBoton(int fila, int columna) {
// Método a completar!.
// En fila y columna se reciben las coordenas donde presionó el usuario, relativas al comienzo de la grilla
// fila 1 y columna 1 corresponden a la posición de arriba a la izquierda.
// Debe indicarse cómo responder al click de ese botón.
    }

}
